sonarcloud: validate project_version

diff --git a/.github/workflows/mkdocs_documentation.yml b/.github/workflows/mkdocs_documentation.yml
--- a/.github/workflows/mkdocs_documentation.yml
+++ b/.github/workflows/mkdocs_documentation.yml
@@ -27,8 +27,15 @@ jobs:
       - name: Install Dependencies
         run: poetry install
       - name: Create new version of mkdocs and publish
+        shell: bash
         run: |
           git config user.name github-actions
           git config user.email github-actions@github.com
-          poetry run mike deploy --push --update-aliases ${{ inputs.project_version }} latest
+          VERSION="${{ inputs.project_version }}"
+          if [[ $VERSION =~ ^[0-9]+(\.[0-9]+)*$ ]]; then
+          poetry run mike deploy --push --update-aliases "$VERSION" latest
           poetry run mike set-default --push latest
+          else
+          echo "Invalid version format: $VERSION"
+          exit 1
+          fi
