Fix sonarcloud issues

diff --git a/.github/workflows/version_upgrade.yml b/.github/workflows/version_upgrade.yml
--- a/.github/workflows/version_upgrade.yml
+++ b/.github/workflows/version_upgrade.yml
@@ -15,7 +15,6 @@ on:
       project_version:
         value: ${{ jobs.upgrade-version.outputs.job_output_version}}
 
-
 jobs:
   upgrade-version:
     runs-on: ubuntu-latest
@@ -38,6 +37,12 @@ jobs:
         uses: abatilo/actions-poetry@v2
         with:
           poetry-version: 1.4.2
+      - name: Validate RELEASE_TYPE
+        run: |
+          if ! [[ "$RELEASE_TYPE" =~ ^(major|minor|patch)$ ]]; then
+            echo "Invalid RELEASE_TYPE: $RELEASE_TYPE" >&2
+            exit 1
+          fi
       - name: bump version and update template_input.yaml
         id: get-version
         run: |
@@ -52,5 +57,5 @@ jobs:
           PROJECT_VERSION=$(poetry version --short)
           git add template_input.yaml
           git add pyproject.toml
-          git commit -m "bump "$RELEASE_TYPE" version: ${{ steps.get-version.outputs.PROJECT_VERSION }}"
+          git commit -m "bump $RELEASE_TYPE version: ${{ steps.get-version.outputs.PROJECT_VERSION }}"
           git push
